version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_value:/code/django_auth/static/

  nginx:
    container_name: nginx
    image: nginx:1.21.1
    restart: unless-stopped
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static_value:/var/html/static/
    ports:
      - 80:80
      - 443:443

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  static_value:
