# Generated by Django 4.0.5 on 2022-06-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
