# Generated by Django 4.0.5 on 2022-06-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_managers_user_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated_code',
        ),
    ]
